/**
 * The frame driver: one NTSC frame, forever.
 *
 * Counted WSYNCs, not the RIOT timer. `tests/fixtures/timing/wsync-only.asm` is
 * the ROM Stella validated at 262 lines; `timer-only.asm`'s T is still marked
 * PENDING a Stella reading in `timing-fixtures.test.ts`, and the reference
 * kernel's own two timer constants were both off by one until a measurement
 * corrected them. Building the first compiler-emitted ROM on the unvalidated
 * mechanism would put an unmeasured number underneath everything increment 5b
 * claims to check. TIM64T arrives when its measurement does.
 */

import { registerEquates } from './registers.ts';

/**
 * SPEC 3: NTSC is 3 VSYNC + 37 VBLANK + 192 visible + 30 overscan.
 *
 * These live in the runtime because they are what the emitted ROM spends, and
 * the compiler's ledger imports them from here. Two copies of 192 -- one the
 * ledger gates on, one the ROM counts down -- is two places to disagree, and
 * the disagreement would be a frame that balances on paper and is short on the
 * screen. That is the exact defect the ledger exists to catch.
 */
export const NTSC_VSYNC_LINES = 3;
export const NTSC_VBLANK_LINES = 37;
export const NTSC_VISIBLE_LINES = 192;
export const NTSC_OVERSCAN_LINES = 30;

/** Frame-absolute number of the first visible scanline. */
export const NTSC_FIRST_VISIBLE_LINE = NTSC_VSYNC_LINES + NTSC_VBLANK_LINES;

export interface FrameOptions {
  /**
   * Zero-page symbols, as `name = $XX` equates.
   *
   * Equates rather than `ds` reservations: `ds` would make the assembler decide
   * where each byte lands, and the compiler's RAM allocator has already decided.
   * Two things assigning addresses is two answers to which byte is free.
   */
  readonly ram: readonly string[];
  /** Assembly lines run once at reset, after RAM and the TIA are cleared. */
  readonly init: readonly string[];
  /** Assembly lines for per-frame setup, run inside vertical blank. */
  readonly setup: readonly string[];
  /**
   * Scanlines `setup` consumes.
   *
   * Passed in rather than counted here. The caller built `setup` out of
   * routines whose line costs the catalog declares, so it KNOWS this; a frame
   * driver that guessed would be deriving a number somebody already measured.
   * Getting it wrong is the most likely bug in this file -- all three kernel
   * fixtures hit it -- which is why it is a parameter with a gate rather than
   * an assumption.
   */
  readonly setupLines: number;
  /** Assembly lines for the visible region, in order. */
  readonly kernel: readonly string[];
  /** Subroutines and tables, placed after the frame loop. */
  readonly data: readonly string[];
}

/** A counted `sta WSYNC` loop, or nothing at all when the count is zero. */
function wsyncLoop(count: number, label: string): string[] {
  if (count === 0) return [];
  if (count === 1) return ['    sta WSYNC'];
  return [`    ldx #${count}`, label, '    sta WSYNC', '    dex', `    bne ${label}`];
}

/**
 * Wrap a visible-region kernel in a complete NTSC frame loop.
 *
 * Returns a whole assembler source: equates, reset, the frame loop, the
 * caller's data, and the vectors. "Frame" names what the emitted program's job
 * is, not how much of the file it covers.
 */
export function emitFrame(options: FrameOptions): string[] {
  const { ram, init, setup, setupLines, kernel, data } = options;

  const blankRemaining = NTSC_VBLANK_LINES - setupLines;
  if (blankRemaining < 1) {
    throw new Error(
      `setup spends ${setupLines} scanlines of the ${NTSC_VBLANK_LINES}-line vertical ` +
        'blank, which leaves none for the WSYNC that must immediately precede the ' +
        'VBLANK write',
    );
  }

  return [
    '; Generated by the Player1DSL compiler. Do not edit.',
    ';',
    '; NTSC frame structure is counted in WSYNCs rather than bounded by TIM64T:',
    '; every scanline below is one `sta WSYNC` that provably executed.',
    '',
    '    processor 6502',
    '',
    ...registerEquates(),
    '',
    "; Zero page, from the compiler's RAM allocator. The stack grows down into",
    '; the same 128 bytes, which is why the allocator reserves the top of them.',
    ...ram,
    '',
    '    seg code',
    '    org $F000',
    '',
    'Reset',
    '    sei                     ; IRQ and NMI are not bonded out on the 6507',
    '    cld                     ; decimal mode exists on this CPU; keep it off',
    '    ldx #$FF',
    '    txs                     ; the stack grows down from $FF',
    '    lda #0',
    '.clearMem',
    '    sta $00,x               ; clears TIA registers $00-$7F and RAM $80-$FF',
    '    dex',
    '    bne .clearMem',
    '    sta $00                 ; x wrapped past 0; clear location $00 too',
    '',
    ...init,
    '',
    'MainLoop',
    `; --- vertical sync: ${NTSC_VSYNC_LINES} lines ---`,
    '    lda #2',
    '    sta VSYNC',
    ...wsyncLoop(NTSC_VSYNC_LINES, '.vsync'),
    '    lda #0',
    '    sta VSYNC',
    '',
    `; --- vertical blank: ${NTSC_VBLANK_LINES} lines, ${setupLines} of them inside setup ---`,
    ...setup,
    '    lda #0                  ; survives the loop below; WSYNC does not touch A',
    ...wsyncLoop(blankRemaining - 1, '.vblank'),
    // The last vertical-blank WSYNC is emitted OUTSIDE the loop, with nothing
    // between it and the VBLANK write. The visible kernel's first row group
    // writes PF0, whose deadline is pixel 0, and the two cycles a `dex`/`bne`
    // fall-through would spend here come straight out of that line's
    // horizontal blank. The reference reaches its last write on this line at
    // colour clock 66 of 68; there is no room to give away.
    '    sta WSYNC',
    '    sta VBLANK              ; blanking off; the visible region starts here',
    '',
    `; --- visible: ${NTSC_VISIBLE_LINES} lines ---`,
    ...kernel,
    '',
    `; --- overscan: ${NTSC_OVERSCAN_LINES} lines ---`,
    '    lda #2',
    '    sta VBLANK              ; blanking on',
    ...wsyncLoop(NTSC_OVERSCAN_LINES, '.overscan'),
    '    jmp MainLoop',
    '',
    ...data,
    '',
    '; The vectors sit in the top 6 bytes of the bank, which is also what makes',
    '; the emitted image exactly 4096 bytes.',
    '    org $FFFC',
    '    .word Reset',
    '    .word Reset',
  ];
}
